# Generated by Django 4.0.6 on 2022-08-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': True},
        ),
    ]
