# Generated by Django 4.0.6 on 2022-08-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_stations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': False},
        ),
    ]
